import { xOracleListType } from 'src/types';

export const xOracleList: xOracleListType = {
  usdc: { primary: ['pyth'], secondary: [] },
  sbeth: { primary: ['pyth'], secondary: [] },
  sbusdt: { primary: ['pyth'], secondary: [] },
  sbwbtc: { primary: ['pyth'], secondary: [] },
  weth: { primary: ['pyth'], secondary: [] },
  wbtc: { primary: ['pyth'], secondary: [] },
  wusdc: { primary: ['pyth'], secondary: [] },
  wusdt: { primary: ['pyth'], secondary: [] },
  sui: { primary: ['pyth'], secondary: [] },
  wapt: { primary: ['pyth'], secondary: [] },
  wsol: { primary: ['pyth'], secondary: [] },
  cetus: { primary: ['pyth'], secondary: [] },
  afsui: { primary: ['pyth'], secondary: [] },
  hasui: { primary: ['pyth'], secondary: [] },
  vsui: { primary: ['pyth'], secondary: [] },
  sca: { primary: ['pyth'], secondary: [] },
  fud: { primary: ['pyth'], secondary: [] },
  deep: { primary: ['pyth'], secondary: [] },
  fdusd: { primary: ['pyth'], secondary: [] },
  blub: { primary: ['pyth'], secondary: [] },
  musd: { primary: ['pyth'], secondary: [] },
  ns: { primary: ['pyth'], secondary: [] },
  usdy: { primary: ['pyth'], secondary: [] },
};
