import { AddressesInterface } from './types.js';

export const EMPTY_ADDRESSES: AddressesInterface = {
  core: {
    version: '',
    versionCap: '',
    object: '',
    market: '',
    adminCap: '',
    coinDecimalsRegistry: '',
    obligationAccessStore: '',
    coins: {
      cetus: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      wapt: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      wsol: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      wbtc: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      weth: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      wusdc: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      wusdt: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      sui: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      afsui: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      hasui: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      vsui: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
      sca: {
        id: '',
        metaData: '',
        treasury: '',
        symbol: '',
        coinType: '',
        decimals: 0,
        oracle: {
          supra: '',
          switchboard: '',
          pyth: {
            feed: '',
            feedObject: '',
          },
        },
      },
    },
    oracles: {
      xOracle: '',
      xOracleCap: '',
      primaryPriceUpdatePolicyObject: '',
      secondaryPriceUpdatePolicyObject: '',
      primaryPriceUpdatePolicyVecsetId: '',
      secondaryPriceUpdatePolicyVecsetId: '',
      supra: { registry: '', registryCap: '', holder: '' },
      switchboard: {
        registry: '',
        registryCap: '',
        registryTableId: '',
        state: '',
      },
      pyth: {
        registry: '',
        registryCap: '',
        state: '',
        wormhole: '',
        wormholeState: '',
      },
    },
    packages: {
      coinDecimalsRegistry: {
        id: '',
        upgradeCap: '',
      },
      math: {
        id: '',
        upgradeCap: '',
      },
      whitelist: {
        id: '',
        upgradeCap: '',
      },
      x: {
        id: '',
        upgradeCap: '',
      },
      protocol: {
        id: '',
        upgradeCap: '',
      },
      protocolWhitelist: {
        id: '',
        upgradeCap: '',
      },
      query: {
        id: '',
        upgradeCap: '',
      },
      supra: { id: '', upgradeCap: '' },
      pyth: {
        id: '',
        upgradeCap: '',
      },
      switchboard: { id: '', upgradeCap: '' },
      xOracle: {
        id: '',
        upgradeCap: '',
      },
      testCoin: { id: '', upgradeCap: '' },
    },
  },
  spool: {
    id: '',
    adminCap: '',
    object: '',
    pools: {
      sweth: {
        id: '',
        rewardPoolId: '',
      },
      ssui: {
        id: '',
        rewardPoolId: '',
      },
      swusdc: {
        id: '',
        rewardPoolId: '',
      },
      swusdt: {
        id: '',
        rewardPoolId: '',
      },
      scetus: {
        id: '',
        rewardPoolId: '',
      },
      safsui: {
        id: '',
        rewardPoolId: '',
      },
      shasui: {
        id: '',
        rewardPoolId: '',
      },
      svsui: {
        id: '',
        rewardPoolId: '',
      },
    },
    config: '',
  },
  borrowIncentive: {
    id: '',
    adminCap: '',
    object: '',
    query: '',
    incentivePools: '',
    incentiveAccounts: '',
    incentiveAccountsTableId: '',
    config: '',
  },
  vesca: {
    id: '',
    object: '',
    adminCap: '',
    tableId: '',
    table: '',
    treasury: '',
    config: '',
    subsTable: '',
    subsTableId: '',
    subsWhitelist: '',
  },
  referral: {
    id: '',
    version: '',
    object: '',
    adminCap: '',
    referralBindings: '',
    bindingTableId: '',
    referralRevenuePool: '',
    revenueTableId: '',
    referralTiers: '',
    tiersTableId: '',
    authorizedWitnessList: '',
  },
  loyaltyProgram: {
    id: '',
    object: '',
    rewardPool: '',
    userRewardTableId: '',
  },
  veScaLoyaltyProgram: {
    id: '',
    object: '',
    veScaRewardPool: '',
    veScaRewardTableId: '',
  },
  scoin: {
    id: '',
    coins: {
      ssui: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      scetus: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      ssca: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      swusdc: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      swusdt: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      sweth: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      safsui: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      shasui: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
      svsui: {
        coinType: '',
        treasury: '',
        metaData: '',
        symbol: '',
      },
    },
  },
};
